name: Launch Tests

on: [push, pull_request] # Will trigger whenever a push is made to the branch, regardless of which branch

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest # Running on this OS, if we need it changed lmk
    steps:
      - uses: actions/checkout@v2 # Checkout repo to remote machine
      - name: Set up OpenJDK17 
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Run Launch Test
        id: tests # Unique ID to reference later to color our message
        run: |
          sudo apt install xvfb
          cd $GRADLE_DIR
          chmod +x ./gradlew
          chmod +x ./headless_run.sh
          ./headless_run.sh
        env:
          GRADLE_DIR: 'source' # Modify this to wherever './gradlew' is 
      - name: Archive game screenshot
        uses: actions/upload-artifact@v3
        with:
          name: game-screenshot
          path: source/game_launched.xwd
      - name: Test Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
           severity: info
           username: GitHub
           details: Test Succeeded!
           webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
           severity: error
           username: GitHub
           details: Test Failed!
           webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
           
      - name: Test Cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
           severity: warn
           username: GitHub
           details: Test Cancelled!
           webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
